version: '2'

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker-postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: